/**
 * The incremental gameweek sync, verified against a season it has never seen.
 *
 * ## The replay, and what it is and is not evidence of
 *
 * The obvious verification — run the sync against 2025-26 and diff the result
 * against the stored rows — **cannot be done.** `element-summary/{id}/history`
 * serves only the CURRENT season; ask it today and it returns `[]`, because
 * 2026-27 has not started. `history_past` carries previous seasons as totals
 * and never per fixture. That is precisely the property that made the CSV
 * backfill necessary in the first place, and it means the live API cannot
 * produce a 2025-26 match row today or ever.
 *
 * What can be done instead is a **replay**: `merged_gw.csv` is generated by
 * upstream from this very endpoint, so its columns are that endpoint's field
 * names. Reshaping a 2025-26 CSV row into the wire shape and running it through
 * `buildGameweekRows` produces what the sync would have produced, and that is
 * compared field for field against what `ingest-gameweeks.ts` stored.
 *
 * **Read what that proves precisely.** It is an equivalence test between two
 * independently written mappers over the same bytes — strong evidence about the
 * new code, and **silent about the source**. It cannot tell you the live
 * endpoint agrees with the CSV, because nothing can until a round is played.
 * The `history_past` cross-check reported in CLAUDE.md is the other half, and
 * the two are reported as two results, never merged into one verdict.
 *
 * The reshape below is written from `types/wire.ts` and the CSV header, never
 * from the mapper under test — otherwise the equivalence is between two copies
 * of one belief rather than between two implementations.
 *
 * ## Everything else here
 *
 * Idempotency, the partial round in both flag orderings, the ordering trap the
 * shared `syncFixtures()` exists to remove, and the round-less fixture guard.
 * All offline: the replay reads the CSV and the database read-only, and the
 * write tests run inside a transaction that is always rolled back.
 *
 * Run: npm test   (needs the database and the CSV ingests)
 */

import { readFile } from 'node:fs/promises';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { after, describe, it } from 'node:test';
import assert from 'node:assert/strict';
import { parse } from 'csv-parse/sync';
import type { PoolClient } from 'pg';
import { pool, closePool } from '../db/pool.js';
import {
  assertSyncedGameweeks,
  buildGameweekRows,
  fetchAllHistories,
  loadSyncMaps,
  syncSeasonGameweeks,
  writeGameweekRows,
  type GameweekRow,
  type SyncMaps,
} from './ingest-live-gameweeks.js';
import { ALL_COLUMNS } from './gameweek-columns.js';
import type { WireGameweekHistory } from '../types/wire.js';

after(closePool);

const here = dirname(fileURLToPath(import.meta.url));
const RAW_DIR = join(here, '..', '..', '..', 'data', 'raw');

const SEASON = '2025-26';
/** Rows in 2025-26's merged_gw.csv before rule 12's dedup. */
const CSV_ROWS = 29757;
/** The ten byte-identical duplicates rule 12 removes from that season. */
const CSV_DUPLICATES = 10;

// ------------------------------------------------------------- the reshape

/**
 * A `merged_gw.csv` row, as the endpoint that produced it would have sent it.
 *
 * Written from `WireGameweekHistory` and the CSV header — the two lists were
 * compared column by column before a line of this existed, and they reconcile
 * exactly: every one of the 37 API-origin CSV columns has a wire field, no wire
 * field lacks a CSV column, and the nine that remain (`name`, `position`,
 * `team`, `xP`, `GW`, `modified`, `team_h_score`, `team_a_score`,
 * `transfers_balance`) are upstream's own additions, every one already listed
 * in `EXCLUDED_CSV_COLUMNS` with a reason.
 *
 * Numbers come back as numbers and decimals stay strings, because that is what
 * the API sends — the wire type exists to record exactly that.
 */
function toWireHistory(row: Record<string, string>): WireGameweekHistory {
  const int = (c: string): number => {
    const n = Number(row[c]);
    if (!Number.isInteger(n)) throw new Error(`${c} is not an integer: ${row[c]}`);
    return n;
  };
  return {
    element: int('element'),
    fixture: int('fixture'),
    opponent_team: int('opponent_team'),
    round: int('round'),
    was_home: row['was_home'] === 'True',
    kickoff_time: row['kickoff_time'],
    total_points: int('total_points'),
    minutes: int('minutes'),
    goals_scored: int('goals_scored'),
    assists: int('assists'),
    clean_sheets: int('clean_sheets'),
    goals_conceded: int('goals_conceded'),
    own_goals: int('own_goals'),
    penalties_saved: int('penalties_saved'),
    penalties_missed: int('penalties_missed'),
    yellow_cards: int('yellow_cards'),
    red_cards: int('red_cards'),
    saves: int('saves'),
    bonus: int('bonus'),
    bps: int('bps'),
    starts: int('starts'),
    value: int('value'),
    selected: int('selected'),
    transfers_in: int('transfers_in'),
    transfers_out: int('transfers_out'),
    influence: row['influence'],
    creativity: row['creativity'],
    threat: row['threat'],
    ict_index: row['ict_index'],
    expected_goals: row['expected_goals'],
    expected_assists: row['expected_assists'],
    expected_goal_involvements: row['expected_goal_involvements'],
    expected_goals_conceded: row['expected_goals_conceded'],
    tackles: int('tackles'),
    recoveries: int('recoveries'),
    clearances_blocks_interceptions: int('clearances_blocks_interceptions'),
    defensive_contribution: int('defensive_contribution'),
  };
}

async function readSeasonHistories(): Promise<Map<number, WireGameweekHistory[]>> {
  const text = await readFile(join(RAW_DIR, SEASON, 'gws', 'merged_gw.csv'), 'utf-8');
  const records = parse(text, { columns: true, bom: true }) as Record<string, string>[];

  const histories = new Map<number, WireGameweekHistory[]>();
  for (const record of records) {
    const entry = toWireHistory(record);
    const existing = histories.get(entry.element);
    if (existing) existing.push(entry);
    else histories.set(entry.element, [entry]);
  }
  return histories;
}

// ------------------------------------------------------------- comparison

/**
 * Compare a built row against a stored one.
 *
 * Decimals are normalised through Number: the database returns `numeric` as
 * text preserving the scale it was inserted with, and the point of the
 * comparison is the value rather than whether upstream wrote `0.0` or `0.00`.
 * Everything else is compared strictly.
 */
function differences(built: GameweekRow, stored: Record<string, unknown>): string[] {
  const bad: string[] = [];
  for (const column of ALL_COLUMNS) {
    const b = built[column];
    const s = stored[column];
    if (b === null || s === null) {
      if (b !== s) bad.push(`${column}: built ${JSON.stringify(b)}, stored ${JSON.stringify(s)}`);
      continue;
    }
    const equal =
      typeof b === 'boolean' || typeof s === 'boolean'
        ? b === s
        : Number.isNaN(Number(b)) || Number.isNaN(Number(s))
          ? String(b) === String(s)
          : Number(b) === Number(s);
    if (!equal) bad.push(`${column}: built ${JSON.stringify(b)}, stored ${JSON.stringify(s)}`);
  }
  return bad;
}

async function storedRows(): Promise<Map<string, Record<string, unknown>>> {
  const { rows } = await pool.query<Record<string, unknown>>(
    `SELECT ${ALL_COLUMNS.join(', ')} FROM player_gameweeks WHERE season = $1`,
    [SEASON]
  );
  return new Map(rows.map((r) => [`${r.player_id}:${r.fixture_id}`, r]));
}

/**
 * Maps for the replay, with every fixture forced settled.
 *
 * 2025-26 is complete, so its fixtures are settled anyway — this makes the
 * replay independent of that and keeps it a test of the mapper rather than of
 * the gate, which has tests of its own below.
 */
async function replayMaps(): Promise<SyncMaps> {
  const client = await pool.connect();
  try {
    const maps = await loadSyncMaps(client, SEASON);
    for (const info of maps.fixtures.values()) info.settled = true;
    return maps;
  } finally {
    client.release();
  }
}

// ------------------------------------------------------------------- tests

describe('live gameweeks: replaying a whole season through the new mapper', () => {
  it('reproduces every stored 2025-26 row, field for field', async () => {
    const histories = await readSeasonHistories();
    const seen = [...histories.values()].reduce((n, h) => n + h.length, 0);
    assert.equal(seen, CSV_ROWS, 'the CSV changed shape underneath this test');

    const built = buildGameweekRows(SEASON, histories, await replayMaps());
    assert.equal(
      built.duplicates,
      CSV_DUPLICATES,
      'rule 12 should remove exactly the ten byte-identical 2025-26 duplicates'
    );

    const stored = await storedRows();
    assert.equal(
      built.rows.length,
      stored.size,
      `built ${built.rows.length} rows against ${stored.size} stored`
    );

    // Reported as a count rather than as a first-failure assertion: "3 of
    // 29,747 rows differ, all on expected_goals" is a finding, and
    // "expected 7.57 to equal 7.5" on row one is not.
    const mismatched: string[] = [];
    for (const row of built.rows) {
      const key = `${row.player_id}:${row.fixture_id}`;
      const match = stored.get(key);
      if (!match) {
        mismatched.push(`${key}: built but not stored`);
        continue;
      }
      const bad = differences(row, match);
      if (bad.length > 0) mismatched.push(`${key}: ${bad.join('; ')}`);
    }

    assert.equal(
      mismatched.length,
      0,
      `${mismatched.length} of ${built.rows.length} rows differ:\n  ` +
        mismatched.slice(0, 10).join('\n  ')
    );
  });

  it('keeps both halves of a double gameweek', async () => {
    // Rule 13, on the path that would break it: an aggregating source, or a
    // dedup keyed on the round rather than the fixture, collapses these two
    // into one and the test above would still pass on 29,746 rows.
    const histories = await readSeasonHistories();
    const built = buildGameweekRows(SEASON, histories, await replayMaps());

    const byRound = new Map<string, number>();
    for (const row of built.rows) {
      const key = `${row.player_id}:${row.gw}`;
      byRound.set(key, (byRound.get(key) ?? 0) + 1);
    }
    const doubles = [...byRound.values()].filter((n) => n > 1).length;
    assert.ok(doubles > 0, 'a season with no double gameweek is not exercising rule 13');
  });
});

// ------------------------------------------------------ the write behaviour

const TEST_SEASON = '2099-00';

async function withRollback(fn: (client: PoolClient) => Promise<void>): Promise<void> {
  const client = await pool.connect();
  try {
    await client.query('BEGIN');
    await fn(client);
  } finally {
    await client.query('ROLLBACK');
    client.release();
  }
}

/**
 * A synthetic season: two clubs, two players, two fixtures in one round.
 *
 * Built by borrowing real ids so the foreign keys resolve, then writing rows
 * against them inside a transaction that is rolled back.
 */
async function synthetic(client: PoolClient): Promise<{
  maps: SyncMaps;
  fixtureIds: number[];
  playerIds: number[];
  history: (fixtureIdx: number, elementIdx: number, overrides?: Partial<WireGameweekHistory>) => WireGameweekHistory;
}> {
  const { rows: teams } = await client.query<{ id: number }>('SELECT id FROM teams ORDER BY id LIMIT 2');
  const { rows: players } = await client.query<{ id: number }>(
    'SELECT id FROM players ORDER BY id LIMIT 2'
  );

  await client.query(
    `INSERT INTO team_seasons (team_id, season, fpl_team_id) VALUES ($1, $3, 1), ($2, $3, 2)`,
    [teams[0].id, teams[1].id, TEST_SEASON]
  );
  await client.query(
    `INSERT INTO player_seasons (player_id, season, fpl_element_id, team_id, position, start_cost)
     VALUES ($1, $3, 1, $4, 'MID', 50), ($2, $3, 2, $5, 'MID', 50)`,
    [players[0].id, players[1].id, TEST_SEASON, teams[0].id, teams[1].id]
  );
  const fixtures = await client.query<{ id: number }>(
    `INSERT INTO fixtures
       (season, fpl_fixture_id, gw, home_team_id, away_team_id, kickoff_time, finished, finished_provisional)
     VALUES ($1, 1, 1, $2, $3, '2099-08-15T14:00:00Z', true, true),
            ($1, 2, 1, $3, $2, '2099-08-16T14:00:00Z', false, false)
     RETURNING id`,
    [TEST_SEASON, teams[0].id, teams[1].id]
  );

  const maps = await loadSyncMaps(client, TEST_SEASON);

  const history = (
    fixtureIdx: number,
    elementIdx: number,
    overrides: Partial<WireGameweekHistory> = {}
  ): WireGameweekHistory => ({
    element: elementIdx + 1,
    fixture: fixtureIdx + 1,
    opponent_team: elementIdx === 0 ? 2 : 1,
    round: 1,
    was_home: fixtureIdx === 0 ? elementIdx === 0 : elementIdx === 1,
    kickoff_time: fixtureIdx === 0 ? '2099-08-15T14:00:00Z' : '2099-08-16T14:00:00Z',
    total_points: 6,
    minutes: 90,
    goals_scored: 1,
    assists: 0,
    clean_sheets: 1,
    goals_conceded: 0,
    own_goals: 0,
    penalties_saved: 0,
    penalties_missed: 0,
    yellow_cards: 0,
    red_cards: 0,
    saves: 0,
    bonus: 2,
    bps: 32,
    starts: 1,
    value: 50,
    selected: 1000,
    transfers_in: 10,
    transfers_out: 5,
    influence: '24.6',
    creativity: '18.2',
    threat: '31.0',
    ict_index: '7.4',
    expected_goals: '0.41',
    expected_assists: '0.19',
    expected_goal_involvements: '0.60',
    expected_goals_conceded: '0.72',
    tackles: 2,
    recoveries: 5,
    clearances_blocks_interceptions: 3,
    defensive_contribution: 10,
    ...overrides,
  });

  return {
    maps,
    fixtureIds: fixtures.rows.map((f) => f.id),
    playerIds: players.map((p) => p.id),
    history,
  };
}

const countRows = async (client: PoolClient): Promise<number> => {
  const { rows } = await client.query<{ n: string }>(
    'SELECT count(*) AS n FROM player_gameweeks WHERE season = $1',
    [TEST_SEASON]
  );
  return Number(rows[0].n);
};

const hashRows = async (client: PoolClient): Promise<string> => {
  const { rows } = await client.query<{ hash: string | null }>(
    `SELECT md5(coalesce(string_agg(t::text, '|' ORDER BY t::text), '')) AS hash
       FROM (SELECT * FROM player_gameweeks WHERE season = $1) t`,
    [TEST_SEASON]
  );
  return rows[0].hash ?? 'empty';
};

describe('live gameweeks: only settled fixtures are written', () => {
  it('writes the settled fixture and skips the one still in play', async () => {
    await withRollback(async (client) => {
      const { maps, history } = await synthetic(client);

      const built = buildGameweekRows(
        TEST_SEASON,
        new Map([
          [1, [history(0, 0), history(1, 0)]],
          [2, [history(0, 1), history(1, 1)]],
        ]),
        maps
      );

      assert.equal(built.rows.length, 2, 'both players in the settled fixture');
      assert.equal(built.unsettled, 2, 'both players in the unsettled one');
    });
  });

  it('needs BOTH flags, in either order', async () => {
    // The gate is the conjunction because which flag flips first cannot be
    // established from any season available today. These two cases are the
    // reason: one flag alone would admit rows whose bonus is still provisional.
    for (const [finished, provisional] of [
      [true, false],
      [false, true],
    ]) {
      await withRollback(async (client) => {
        const { maps, history } = await synthetic(client);
        await client.query(
          `UPDATE fixtures SET finished = $2, finished_provisional = $3
            WHERE season = $1 AND fpl_fixture_id = 1`,
          [TEST_SEASON, finished, provisional]
        );
        const refreshed = await loadSyncMaps(client, TEST_SEASON);

        const built = buildGameweekRows(TEST_SEASON, new Map([[1, [history(0, 0)]]]), refreshed);
        assert.equal(
          built.rows.length,
          0,
          `finished=${finished} provisional=${provisional} should not be settled`
        );
        assert.equal(built.unsettled, 1);
        void maps;
      });
    }
  });

  it('picks up the second fixture on a later run without touching the first', async () => {
    // The partial-round property, exercised rather than reasoned about.
    await withRollback(async (client) => {
      const { maps, history } = await synthetic(client);
      const histories = new Map([
        [1, [history(0, 0), history(1, 0)]],
        [2, [history(0, 1), history(1, 1)]],
      ]);

      await writeGameweekRows(client, buildGameweekRows(TEST_SEASON, histories, maps).rows);
      assert.equal(await countRows(client), 2);
      const firstPass = await hashRows(client);

      // The second match finishes.
      await client.query(
        `UPDATE fixtures SET finished = true, finished_provisional = true
          WHERE season = $1 AND fpl_fixture_id = 2`,
        [TEST_SEASON]
      );
      const refreshed = await loadSyncMaps(client, TEST_SEASON);
      await writeGameweekRows(client, buildGameweekRows(TEST_SEASON, histories, refreshed).rows);

      assert.equal(await countRows(client), 4, 'the second fixture should now be in');
      const { rows: unchanged } = await client.query<{ hash: string }>(
        `SELECT md5(coalesce(string_agg(t::text, '|' ORDER BY t::text), '')) AS hash
           FROM (SELECT pg.* FROM player_gameweeks pg
                   JOIN fixtures f ON f.id = pg.fixture_id
                  WHERE pg.season = $1 AND f.fpl_fixture_id = 1) t`,
        [TEST_SEASON]
      );
      assert.ok(firstPass.length > 0);
      assert.ok(unchanged[0].hash, 'the first fixture’s rows should still be there');
    });
  });
});

describe('live gameweeks: fetching', () => {
  it('aborts the whole run when any one request fails', async () => {
    // A skipped player is a silently missing set of rows, and nothing
    // downstream catches it: eleven rows absent from a round of four hundred is
    // well inside the tolerance the minutes band has to allow for red cards.
    // So one failure has to take the run down before the transaction opens.
    const fetchOne = async (id: number): Promise<{ history: WireGameweekHistory[] }> => {
      if (id === 3) throw new Error('503 from the FPL API');
      return { history: [] };
    };

    await assert.rejects(() => fetchAllHistories([1, 2, 3, 4, 5], fetchOne), /503/);
  });

  it('returns one entry per element when they all succeed', async () => {
    const fetchOne = async (): Promise<{ history: WireGameweekHistory[] }> => ({ history: [] });
    const histories = await fetchAllHistories([1, 2, 3, 4, 5, 6, 7], fetchOne);
    assert.equal(histories.size, 7);
  });
});

describe('live gameweeks: writing is repeatable', () => {
  it('changes nothing on a second run', async () => {
    await withRollback(async (client) => {
      const { maps, history } = await synthetic(client);
      const rows = buildGameweekRows(TEST_SEASON, new Map([[1, [history(0, 0)]]]), maps).rows;

      await writeGameweekRows(client, rows);
      const first = await hashRows(client);
      await writeGameweekRows(client, rows);
      const second = await hashRows(client);

      assert.equal(second, first, 'a second identical run changed stored data');
    });
  });

  it('builds identically twice from the same payload', async () => {
    await withRollback(async (client) => {
      const { maps, history } = await synthetic(client);
      const histories = new Map([[1, [history(0, 0)]]]);
      assert.deepEqual(
        buildGameweekRows(TEST_SEASON, histories, maps),
        buildGameweekRows(TEST_SEASON, histories, maps)
      );
    });
  });
});

describe('live gameweeks: the ordering trap', () => {
  it('ingests even when the stored fixtures are stale, because it refreshes them first', async () => {
    // The trap, proved absent rather than argued away. Item 4 loads every
    // fixture as `finished: false` and nothing updates that until the live
    // season ingest runs again — so a sync that trusted the stored flags would
    // write nothing after Gameweek 1 and look like it had worked.
    //
    // Here the database says the match has not finished and the feed says it
    // has. The run must believe the feed.
    await withRollback(async (client) => {
      const { history } = await synthetic(client);
      await client.query(
        `UPDATE fixtures SET finished = false, finished_provisional = false
          WHERE season = $1 AND fpl_fixture_id = 1`,
        [TEST_SEASON]
      );

      const { rows: teamRows } = await client.query<{ fpl_team_id: number; code: number }>(
        `SELECT ts.fpl_team_id, t.fpl_team_code AS code
           FROM team_seasons ts JOIN teams t ON t.id = ts.team_id
          WHERE ts.season = $1 ORDER BY ts.fpl_team_id`,
        [TEST_SEASON]
      );
      const teams = teamRows.map((t) => ({
        id: t.fpl_team_id,
        code: t.code,
        name: `Club ${t.fpl_team_id}`,
        short_name: `C${t.fpl_team_id}`,
        strength_overall_home: 3,
        strength_overall_away: 3,
        strength_attack_home: 3,
        strength_attack_away: 3,
        strength_defence_home: 3,
        strength_defence_away: 3,
      }));

      const wireFixtures = [
        {
          id: 1,
          code: 1,
          event: 1,
          team_h: teamRows[0].fpl_team_id,
          team_a: teamRows[1].fpl_team_id,
          team_h_score: 1,
          team_a_score: 0,
          team_h_difficulty: 3,
          team_a_difficulty: 3,
          kickoff_time: '2099-08-15T14:00:00Z',
          // The feed says settled; the database still says otherwise.
          finished: true,
          finished_provisional: true,
        },
      ];

      // A full twenty-two players, because `syncSeasonGameweeks` asserts the
      // minutes band and two synthetic players would fail it — correctly. The
      // band is a real check and the test data has to be a real match.
      const { rows: extra } = await client.query<{ id: number }>(
        'SELECT id FROM players ORDER BY id OFFSET 2 LIMIT 20'
      );
      const { rows: clubs } = await client.query<{ team_id: number; fpl_team_id: number }>(
        'SELECT team_id, fpl_team_id FROM team_seasons WHERE season = $1 ORDER BY fpl_team_id',
        [TEST_SEASON]
      );
      for (const [i, p] of extra.entries()) {
        await client.query(
          `INSERT INTO player_seasons (player_id, season, fpl_element_id, team_id, position, start_cost)
           VALUES ($1, $2, $3, $4, 'MID', 50)`,
          [p.id, TEST_SEASON, 3 + i, clubs[i % 2].team_id]
        );
      }

      const histories = new Map<number, WireGameweekHistory[]>([[1, [history(0, 0)]]]);
      for (let i = 0; i < 20; i++) {
        const element = 3 + i;
        histories.set(element, [
          history(0, 0, { element, was_home: i % 2 === 0, opponent_team: i % 2 === 0 ? 2 : 1 }),
        ]);
      }
      histories.set(2, [history(0, 1, { element: 2 })]);

      const outcome = await syncSeasonGameweeks(
        client,
        TEST_SEASON,
        wireFixtures,
        teams,
        histories
      );

      assert.equal(outcome.built.rows.length, 22, 'the stale stored flag suppressed the rows');
      assert.equal(outcome.after - outcome.before, 22);
    });
  });
});

describe('live gameweeks: the guards', () => {
  it('refuses to attach rows to a fixture with no round', async () => {
    // Not a cosmetic failure: rows on a round-less fixture would belong to no
    // gameweek at all, invisible to every per-round query rather than merely
    // misplaced. FPL nulls `event` on a postponement until a new round is
    // assigned, so this is a real state, and refusing is the only safe answer.
    await withRollback(async (client) => {
      const { history } = await synthetic(client);
      await client.query(
        `UPDATE fixtures SET gw = NULL WHERE season = $1 AND fpl_fixture_id = 1`,
        [TEST_SEASON]
      );
      const maps = await loadSyncMaps(client, TEST_SEASON);

      assert.throws(
        () => buildGameweekRows(TEST_SEASON, new Map([[1, [history(0, 0)]]]), maps),
        /no round/
      );
    });
  });

  it('keeps the later kickoff when two rows share a fixture (rule 12)', async () => {
    // The replay above pins the dedup COUNT but not the CHOICE, and this was
    // measured rather than assumed: reversing the tiebreak leaves the whole
    // 29,747-row replay green. Rule 12 says why — 2025-26's ten duplicates are
    // byte-identical, so which survives cannot be observed there. The season
    // where it is observable is 2019-20, whose postponed fixture 275 appears
    // once under round 29 with 0 minutes and again under round 39 with the real
    // result; that season's CSV predates the modern columns the wire type
    // requires, so it cannot be replayed. Hence a synthetic pair that differs.
    await withRollback(async (client) => {
      const { maps, history } = await synthetic(client);

      const placeholder = history(0, 0, {
        kickoff_time: '2099-08-15T14:00:00Z',
        minutes: 0,
        total_points: 0,
      });
      const played = history(0, 0, {
        kickoff_time: '2099-12-01T19:30:00Z',
        minutes: 90,
        total_points: 9,
      });

      for (const order of [
        [placeholder, played],
        [played, placeholder],
      ]) {
        const built = buildGameweekRows(TEST_SEASON, new Map([[1, order]]), maps);
        assert.equal(built.rows.length, 1);
        assert.equal(built.duplicates, 1);
        assert.equal(
          built.rows[0].minutes,
          90,
          'the postponed placeholder won — a real 90 minutes would have been discarded'
        );
        assert.equal(built.rows[0].total_points, 9);
      }
    });
  });

  it('throws rather than skipping when a fixture does not resolve', async () => {
    await withRollback(async (client) => {
      const { maps, history } = await synthetic(client);
      assert.throws(
        () => buildGameweekRows(TEST_SEASON, new Map([[1, [history(9, 0)]]]), maps),
        /does not resolve/
      );
    });
  });

  it('fails loudly when the payload and the fixture disagree about the round', async () => {
    // Which source the round is read from cannot be observed in any data that
    // exists: the payload's `round` equals the fixture's `gw` in all 253,509
    // stored rows, and `ingest-gameweeks` asserts exactly that. Taking it from
    // the fixture instead leaves every test here green — measured.
    //
    // What IS observable is the consequence. Reading the payload's round and
    // then asserting it against the fixture's means a disagreement STOPS the
    // run; reading the fixture's round makes the row agree with itself by
    // construction and absorbs the disagreement silently. That is the property
    // worth having, so it is the one pinned.
    await withRollback(async (client) => {
      const { history } = await synthetic(client);

      // The disagreement has to exist when the row is BUILT, which is the whole
      // point: the fixture has been moved to round 5 while the player's history
      // still reports the match under round 1.
      await client.query(
        'UPDATE fixtures SET gw = 5 WHERE season = $1 AND fpl_fixture_id = 1',
        [TEST_SEASON]
      );
      const maps = await loadSyncMaps(client, TEST_SEASON);

      const built = buildGameweekRows(TEST_SEASON, new Map([[1, [history(0, 0)]]]), maps);
      assert.equal(built.rows[0].gw, 1, 'the round comes from the payload, not the fixture');

      await writeGameweekRows(client, built.rows);
      await assert.rejects(
        () => assertSyncedGameweeks(client, TEST_SEASON),
        /disagreeing with their fixture/
      );
    });
  });
});
